framework:
    workflows:
        # State machine pour les demandes de contrat
        # Les états sont :
        # - created : la demande a été créée
        # - pending_manager_approval : la demande est en attente de validation du manager
        # - pending_legal_department_manager_approval : la demande est en attente de validation du manager juridique
        # - pending_agent_approval : la demande est en attente de validation de l'agent juridique
        # - approved : la demande est validée
        # - rejected_by_manager : la demande a été rejetée par le manager
        # - rejected_by_legal_department_manager : la demande a été rejetée par le manager juridique
        # - rejected_by_agent : la demande a été rejetée par l'agent juridique
        # Pour les permissions, on a :
        # - owner : le propriétaire de la demande
        # - manager : le manager de l'agent
        # - manager_juridique : le manager juridique
        # - user_juridique : l'agent juridique
        # Pour chaque état, on a :
        # - edit : permet de modifier la demande
        # - remove : permet de supprimer la demande
        # - approve : permet de valider la demande
        # - approve_manager : permet de transférer la demande au manager juridique
        # - transfer : permet de transférer la demande à un autre agent juridique pour validation
        contract_request:
            type: state_machine
            marking_store:
                type: method
                property: currentState
            supports:
                - App\Entity\Contrat\Contrat
            initial_marking: created
            places:
                created:
                    metadata:
                        label: Demande créée
                        color: blue
                pending_manager_approval:
                    metadata:
                        label: En attente de validation du manager
                        color: default
                        permissions:
                            owner:
                                edit: true
                                remove: true
                            manager:
                                approve_manager: true
                                edit: true
                            manager_juridique:
                                - none
                            user_juridique:
                                - none
                pending_legal_department_manager_approval:
                    metadata:
                        label: En attente de validation du manager juridique
                        color: primary
                        permissions:
                            owner:
                                - none
                            manager:
                                - none
                            manager_juridique:
                                approve: true
                                edit: true
                                transfer: true
                            user_juridique:
                                - none
                pending_agent_approval:
                    metadata:
                        label: En attente de validation de l'agent
                        color: secondary
                        permissions:
                            owner:
                                - none
                            manager:
                                - none
                            manager_juridique:
                                - none
                            user_juridique:
                                approve: true
                                edit: true
                approved:
                    metadata:
                        label: Validé
                        color: success
                        permissions:
                            owner:
                                - none
                            manager:
                                - none
                            manager_juridique:
                                edit: true
                            user_juridique:
                                edit: true
                rejected_by_manager:
                    metadata:
                        label: Rejeté par le manager
                        color: danger
                        permissions:
                            owner:
                                - none
                            manager:
                                - none
                            manager_juridique:
                                - none
                            user_juridique:
                                - none
                rejected_by_legal_department_manager:
                    metadata:
                        label: Rejeté par le manager juridique
                        color: danger
                        permissions:
                            owner:
                                - none
                            manager:
                                - none
                            manager_juridique:
                                - none
                            user_juridique:
                                - none
                rejected_by_agent:
                    metadata:
                        label: Rejeté par l'agent juridique
                        color: danger
                        permissions:
                            owner:
                                - none
                            manager:
                                - none
                            manager_juridique:
                                - none
                            user_juridique:
                                - none
            transitions:
                submit:
                    from: created
                    to: pending_manager_approval
                submit_by_juridique:
                    from: created
                    to: approved
                approve_manager:
                    from: pending_manager_approval
                    to: pending_legal_department_manager_approval
                approve_legal_department:
                    from: pending_legal_department_manager_approval
                    to: approved
                reassign_to_agent:
                    from: pending_legal_department_manager_approval
                    to: pending_agent_approval
                approve_agent:
                    from: pending_agent_approval
                    to: approved
                reject_manager:
                    from: pending_manager_approval
                    to: rejected_by_manager
                reject_legal_department:
                    from: pending_legal_department_manager_approval
                    to: rejected_by_legal_department_manager
                reject_agent:
                    from: pending_agent_approval
                    to: rejected_by_agent
